service: graphql-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1  # Change to your preferred AWS region

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

