name: Deploy Serverless App

on:
  push:
    branches:
      - main  # Run when changes are pushed to `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Serverless CLI
        run: npm install -g serverless

      # ✅ Authenticate with Serverless Framework using Access Key
      - name: Authenticate with Serverless
        run: echo "SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test || echo "No tests found, skipping"

      # ✅ Deploy using Serverless Framework
      - name: Deploy to AWS Lambda
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
        run: npx serverless deploy
