name: Deploy Serverless App

on:
  push:
    branches:
      - main  # Run when changes are pushed to `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Node.js Version
        run: node -v  # Logs the Node.js version

      - name: Set Up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Reinstall Serverless CLI
        run: |
          npm uninstall -g serverless || true
          npm install -g serverless
          serverless -v  # Logs the Serverless version

      - name: Authenticate with Serverless
        uses: serverless/github-action@v3
        with:
          serverless-access-key: ${{ secrets.SERVERLESS_ACCESS_KEY }}

      - name: Clean & Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run Tests
        run: npm test || echo "No tests found, skipping"

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"  # Change to your AWS region
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: npx serverless deploy



