name: Deploy Serverless App

on:
  push:
    branches:
      - main  # Run when changes are pushed to `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test  # Ensure you have tests configured

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"  # Change to your AWS region
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          npm install -g serverless
          echo "service: my-serverless-app" > serverless.yml
          echo "provider:" >> serverless.yml
          echo "  name: aws" >> serverless.yml
          echo "  runtime: nodejs18.x" >> serverless.yml
          echo "functions:" >> serverless.yml
          echo "  hello:" >> serverless.yml
          echo "    handler: handler.hello" >> serverless.yml
          serverless deploy

