name: Deploy Serverless App

on:
  push:
    branches:
      - main  # Run when changes are pushed to `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Log Node.js version
      - name: Check Node.js Version
        run: node -v

      # ✅ Set Up Node.js 18
      - name: Set Up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ✅ Install Serverless CLI & Authenticate
      - name: Install Serverless CLI
        run: npm install -g serverless

      - name: Authenticate with Serverless
        run: npx serverless login --org my-org --app my-app

      # ✅ Install Dependencies
      - name: Clean & Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      # ✅ Run Tests (Optional)
      - name: Run Tests
        run: npm test || echo "No tests found, skipping"

      # ✅ Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"  # Change to your AWS region
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: npx serverless deploy
